adding transition
yshui/picom pull request #752
Opened 2021-12-24 12:24 UTC by Arian8j2

So this is my first ever PR and I'm not that much familiar with Picom code base yet and i really understand if not wanna merge it, But i said give it a try, So This PR adds transition similar to CSS transitions for simple transforms. I created a demo GIF to get the idea.
![demo](https://user-images.githubusercontent.com/56799194/147352310-7c5387da-0cbe-4e86-b1b6-cc47c2b77126.gif)

2022-01-14 17:12 UTC, godalming123 commented
Is it possible to make the transition direction depend on wether your going to the next/previos workspace instead of just what app is transitioning. @Arian8j2

2022-01-14 17:17 UTC, godalming123 reviewed
This looks great from the gif I havent looked at how clean the code is but so far so good! I would suggest one change though which is to update the manpage so it tells you about these new property's

2022-01-14 21:24 UTC, Arian8j2 commented
> Is it possible to make the transition direction depend on wether your going to the next/previos workspace instead of just what app is transitioning.
> 
> Sorry I see you can use
> 
> ```
> transition-direction = "smart-x";
> ```
> 
> or
> 
> ```
> transition-direction = "smart-x";
> ```
> 
> for this functionality.

I don't think any way exists to find out which workspace is currently on because there are lot's of different window manager out there. So basically `smart-x` and `smart-y` are not related to work spaces, they look for window width and if thats greater than 80% of screen width or window gets like whole screen it change direction of that window to `left` or `up` and so on...



> This looks great from the gif I havent looked at how clean the code is but so far so good! I would suggest one change though which is to update the manpage so it tells you about these new property's.

Happy to hear you enjoyed the looks, I totally forgot about man pages but will look for it in the future, Thanks mentioning that.

2022-01-22 17:23 UTC, yshui requested changes
Thanks for your work!

In general I have some reservation about the compositor moving users window around (changing opacity/color/etc is fine). The reason being the confusion this could cause, because although the window is shown at a certain location on screen, it doesn't accept user interaction at that location.

But I guess it is for the user to decide whether they want this. So I won't reject this PR on that ground.

This PR is somewhat messy, I would like to see some clean ups:
* bug fixes shouldn't be in separate commits. each commit should not have _known_ bugs at the time of merge.
* changes should be splitted into smaller commits. this is to make it easier in the future to locate origin of bugs. as an example, for this PR, you could split it into:
    * add config options
    * add easing functions
    * implement transition
    * implement transition rules.

As a side note, I wonder if the current fade-in/fade-out feature can be implemented with the same transition mechanism, if you make it more generic.

2022-01-22 17:23 UTC, yshui commented on picom.sample.conf
> +################################
There is not enough explanation here for:
* what does transition do? i.e. what is being transitioned?
* what is transition-offset?
* what is the meaning of each transition-direction?

2022-01-22 17:23 UTC, yshui commented on src/config.c
> +		.transition_direction = -1,
Wrong indentation size. Can you run clang-format over your changes?

2022-01-22 17:23 UTC, yshui commented on src/picom.c
> +			// TODO: use refresh rate instead of using static 60 fps calculation
I'd like to see this todo completed before merging

2022-01-22 17:23 UTC, yshui commented on src/picom.c
> +			if(direction > TRANSITIONDIR_TOP) {
I don't quite understand the logic here, maybe because it is not explained what the transition directions mean.

2022-01-22 17:23 UTC, yshui commented on src/timing_functions.c
> +#include <math.h>
This file doesn't follow picom's naming convention.

2022-01-24 12:25 UTC, Arian8j2 commented
Moved to #766.

2022-01-24 12:25 UTC, closed without merging